package com.cognizant.agrilink.report.controller;

import com.cognizant.agrilink.report.dto.AgriReportDto;
import com.cognizant.agrilink.report.dto.MessageResponse;
import com.cognizant.agrilink.report.entity.AgriReport;
import com.cognizant.agrilink.report.service.AgriReportService;
import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import jakarta.servlet.http.HttpServletResponse;
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping({"/reports", "/agri-reports"})
@lombok.extern.slf4j.Slf4j
public class AgriReportController {

	private final AgriReportService agriReportService;

	public AgriReportController(AgriReportService agriReportService) {
		this.agriReportService = agriReportService;
	}

	@PostMapping({"/generate", ""})
	public ResponseEntity<MessageResponse> generate(@RequestBody AgriReportDto dto) {
		log.info("Generating report with scope: {}", dto.getScope());
		agriReportService.create(dto);
		return ResponseEntity.ok(new MessageResponse("AgriReport created successfully"));
	}

	@GetMapping({"/fetchAll", ""})
	public ResponseEntity<List<AgriReport>> fetchAll() {
		log.info("Fetching all reports metadata");
		return ResponseEntity.ok(agriReportService.getAll());
	}

	@GetMapping({"/fetchById/{reportId}", "/{reportId}"})
	public ResponseEntity<AgriReport> fetchById(@PathVariable(name = "reportId") Integer reportId) {
		return ResponseEntity.ok(agriReportService.getById(reportId));
	}

	@GetMapping("/fetchByScope/{scope}")
	public ResponseEntity<List<AgriReport>> fetchByScope(@PathVariable String scope) {
		return ResponseEntity.ok(agriReportService.getByScope(scope));
	}

	@PutMapping("/{reportId}")
	public ResponseEntity<MessageResponse> update(@PathVariable(name = "reportId") Integer reportId, @RequestBody AgriReportDto dto) {
		agriReportService.update(reportId, dto);
		return ResponseEntity.ok(new MessageResponse("AgriReport updated successfully"));
	}

	@DeleteMapping({"/delete/{reportId}", "/{reportId}"})
	public ResponseEntity<MessageResponse> delete(@PathVariable(name = "reportId") Integer reportId) {
		agriReportService.delete(reportId);
		return ResponseEntity.ok(new MessageResponse("AgriReport deleted successfully"));
	}

	@PostMapping("/export")
	public void exportReports(@RequestBody Map<String, String> request, HttpServletResponse response) throws Exception {
		String format = request.getOrDefault("format", "excel").toLowerCase();
		List<AgriReport> reports = agriReportService.getAll();

		if ("pdf".equals(format)) {
			response.setContentType("application/pdf");
			response.setHeader(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"reports.pdf\"");
			
			Document document = new Document();
			PdfWriter.getInstance(document, response.getOutputStream());
			document.open();
			document.add(new Paragraph("AgriLink - Generated Reports"));
			document.add(new Paragraph(" "));

			PdfPTable table = new PdfPTable(5);
			table.addCell("Report ID");
			table.addCell("Generated By");
			table.addCell("Scope");
			table.addCell("Metrics");
			table.addCell("Generated Date");

			for (AgriReport report : reports) {
				table.addCell(String.valueOf(report.getReportId()));
				table.addCell(String.valueOf(report.getGeneratedBy()));
				table.addCell(report.getScope());
				table.addCell(report.getMetrics());
				table.addCell(String.valueOf(report.getGeneratedDate()));
			}
			document.add(table);
			document.close();
		} else {
			response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
			response.setHeader(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"reports.xlsx\"");
			
			Workbook workbook = new XSSFWorkbook();
			Sheet sheet = workbook.createSheet("Reports");
			
			Row header = sheet.createRow(0);
			header.createCell(0).setCellValue("Report ID");
			header.createCell(1).setCellValue("Generated By");
			header.createCell(2).setCellValue("Scope");
			header.createCell(3).setCellValue("Metrics");
			header.createCell(4).setCellValue("Generated Date");

			int rowNum = 1;
			for (AgriReport report : reports) {
				Row row = sheet.createRow(rowNum++);
				row.createCell(0).setCellValue(report.getReportId());
				row.createCell(1).setCellValue(report.getGeneratedBy());
				row.createCell(2).setCellValue(report.getScope());
				row.createCell(3).setCellValue(report.getMetrics());
				row.createCell(4).setCellValue(String.valueOf(report.getGeneratedDate()));
			}

			workbook.write(response.getOutputStream());
			workbook.close();
		}
	}
}
