spring.application.name=gateway-service
server.port=9091

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# Resilience4j Circuit Breaker properties
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.configs.default.sliding-window-type=COUNT_BASED


# Request timeout configuration
resilience4j.timelimiter.configs.default.timeout-duration=3s
resilience4j.timelimiter.configs.report-service.timeout-duration=10s
resilience4j.timelimiter.configs.iamServiceCircuit.timeout-duration=10s

# Logging configuration
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.org.springframework.web.servlet.function=DEBUG



